name: CI - ERM Server

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - '.github/workflows/server-ci.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'server/**'
      - '.github/workflows/server-ci.yml'

jobs:
  build_and_test_server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'server/package-lock.json'

      - name: Clear npm cache (Force clean)
        run: npm cache clean --force
        working-directory: ./server

      - name: Install Server Dependencies
        run: npm ci
        working-directory: ./server

      - name: List files and print eslint.config.js
        run: |
          echo "Files in server/:"
          ls -l
          echo ""
          echo "Contents of eslint.config.js:"
          cat eslint.config.js
        working-directory: ./server

      - name: Check ESLint Version
        run: npx eslint --version
        working-directory: ./server

      - name: Run Server Lint
        run: npx eslint . --config ./eslint.config.js
        working-directory: ./server

      - name: Run Server Tests
        run: npm test
        working-directory: ./server
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
