name: CI - ERM Server

on:
  push:
    branches:
      - main # Or 'master', 'develop', etc.
    paths:
      - 'server/**'
      - '.github/workflows/server-ci.yml'
  pull_request:
    branches:
      - main # Or 'master', 'develop', etc.
    paths:
      - 'server/**'
      - '.github/workflows/server-ci.yml'

jobs:
  build_and_test_server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'server/package-lock.json'

      # --- AGGRESSIVE CACHE CLEARING (New Step) ---
      - name: Clear npm cache (Force clean)
        run: npm cache clean --force
        working-directory: ./server
        # Important: Add 'if: always()' to ensure this runs even if previous steps fail,
        # but for clean-up *before* install, it should run normally.

      - name: Install Server Dependencies
        run: npm ci
        working-directory: ./server

      # --- DIAGNOSTIC STEP (New Step) ---
      - name: List files in server directory (for debugging)
        run: |
          echo "Files in server/ directory:"
          ls -R .
          echo "Files in server/__tests__/ directory:"
          ls -R __tests__
        working-directory: ./server

      # --- LINTING STEP (Your existing step) ---
      - name: Run Server Lint
        run: npm run lint
        working-directory: ./server
        # Optional: For deep debugging if linting still fails, you can add --debug
        # run: npm run lint -- --debug


      - name: Run Server Tests
        run: npm test
        working-directory: ./server
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}